.TH "bad_path" 3 "ne 28. kvě 2017" "Version 1.0.0.1" "Reservation system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bad_path \- Vyjimka, rikajici, ze byla zadana nespravna cesta\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exceptions\&.h>\fP
.PP
Dědí z bázové třídy exception\&.
.SS "Veřejné metody"

.in +1c
.ti -1c
.RI "const char * \fBwhat\fP () const override  throw ()"
.br
.in -1c
.SH "Detailní popis"
.PP 
Vyjimka, rikajici, ze byla zadana nespravna cesta\&. 
.PP
Definice je uvedena na řádku 5 v souboru Exceptions\&.h\&.

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Reservation system\&.
