.TH "coordinates" 3 "ne 28. kvě 2017" "Version 1.0.0.1" "Reservation system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coordinates \- Struktura, ktera nam definuje souradnice v budove\&. Rows = x, Columns = y\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Structures\&.h>\fP
.SS "Veřejné atributy"

.in +1c
.ti -1c
.RI "size_t \fBrows\fP"
.br
.RI "x-ova souradnice "
.ti -1c
.RI "size_t \fBcolumns\fP"
.br
.RI "y-ova souradnice "
.in -1c
.SH "Detailní popis"
.PP 
Struktura, ktera nam definuje souradnice v budove\&. Rows = x, Columns = y\&. 
.PP
Definice je uvedena na řádku 5 v souboru Structures\&.h\&.

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Reservation system\&.
